config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  enum status: {waiting: 0, doing: 1, done: 2}
  enum priority: {high: 0, medium: 1, low: 2}
  scope :sort_title, -> (title) { where("title LIKE ?", "%#{title}%") }
  scope :sort_status, -> (status) { where(status: status) }
  scope :user_tasks, -> (current_user_id) { where(user_id: current_user_id).includes(:user) }
  paginates_per 10
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :not_destroy_last_admin
  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, 
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy
  paginates_per 10

  private

  def not_destroy_last_admin
    if User.where(admin: 'true').count == 1 && self.admin?
      errors.add :base, '管理者は必ず１名必要です'
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :non_admin
  helper_method :sort_column, :sort_direction
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録しました"
      redirect_to admin_users_path(@user.id)
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new
    end
  end

  def index
    @users = User.all.order("#{sort_column} #{sort_direction}")
    @users = @users.page params[:page]
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.all.page params[:page]
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path, notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました"
    else
      redirect_to admin_users_path, notice: "#{@user.errors[:base]}"
    end
  end

  private

  def non_admin
    redirect_to tasks_path, notice: "管理者以外はアクセスできません" unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @tasks = Task.user_tasks(current_user.id).order("#{sort_column} #{sort_direction}").page params[:page]
    if params[:search].present?
      title = params[:search][:title]
      status = params[:search][:status]
      labels = params[:search][:label_id]
      if title.present? && status.present?
        @tasks = Task.sort_title(title).sort_status(status).page params[:page]
      elsif title.present?
        @tasks = Task.sort_title(title).page params[:page]
      elsif status.present?
        @tasks = Task.sort_status(status).page params[:page]
      elsif labels.present?
        @tasks = @tasks.joins(:labels).where(labels: { id: labels }).page params[:page]
      end
    end
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "タスクを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました"
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :deadline, :status, :priority, { label_ids:[] })
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : 'deadline'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
    redirect_to tasks_path if current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザー登録しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.all.page params[:page]
    redirect_to tasks_path unless current_user.id == @user.id
  end

  def edit
    @user = User.find(params[:id])
    redirect_to tasks_path unless current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を変更しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end

  def sort_order(column, view_title)
    direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'asc'
    link_to view_title, { sort: column, direction: direction }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
  <%= form_with(model: @user, local: true, url: admin_user_path) do |form| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "つのエラー") %> があるので<%= @user.name %> 情報の更新ができません</h2>
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name %>
            </div><br>
            <div class="field">
              <%= form.label :email %>
              <%= form.email_field :email %>
            </div><br>
              <%= form.label :admin %>
              <%= form.select :admin, [["なし", "false"],["あり", "true"]],include_blank: "選択" %>
            <div class="field">
              <%= form.label :password %>
              <%= form.password_field :password %>
            </div><br>
            <div class="field">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation %>
            </div><br>
            <div class="actions">
              <%= form.submit %>
            </div>
            <% end %>
            <%= link_to 'ユーザー一覧', admin_users_path, class: "btn btn-outline-info" %>

app/views/admin/users/index.html.erb
<section class="vh-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                alt="Check" width="60">
              <h2 class="my-4">管理者用ユーザー管理画面</h2>
            </div>
            <p><%= notice %></p>
            
              <div class="search-form">
                <%= form_with(scope: :search, url: admin_users_path, local: true, method: :get) do |f| %>
                  <%= f.label :ユーザー名検索 %>
                  <%= f.text_field :name %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <div class="new-user-sign-up">
                <%= link_to "新規ユーザー登録", new_admin_user_path %>
              </div>

            <table class="table text-white mb-0">
              <thead>
                <tr>
                  <th scope="col"><div class="user_id"><%= sort_order "id", "ID" %></div></th>
                  <th scope="col"><div class="user_name"><%= sort_order "name", "名前" %></div></th>
                  <th scope="col"><div class="email"><%= sort_order "email", "メールアドレス" %></div></th>
                  <th scope="col"><div class="created_at"><%= sort_order "created_at", "登録日" %></div></th>
                  <th scope="col"><div class="tasks-count"><%= sort_order "tasks_count", "タスク数" %></div></th>
                  <th scope="col"><div class="admin"><%= sort_order "admin", "管理者" %></div></th>
                </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <div class="task-preview">
                  <tr class="fw-normal">
                    <td class="align-middle"><span><div class="user_id"><%= user.id %></span></div></td>
                    <td class="align-middle"><span><div class="user_name"><%= user.name %></span></div></td>
                    <td class="align-middle"><span><div class="user_email"><%= user.email %></span></div></td>
                    <td class="align-middle"><span><div class="user_created_at"><%= user.created_at.strftime('%Y/%m/%d') %></span></div></td>
                    <td class="align-middle"><span><div class="user_updated_te"><%= user.tasks.count %></span></div></td>
                    <td class="align-middle"><h6 class="mb-0"><span class="badge bg-danger"><div class="user_admin"><%= user.admin %></span></h6></div></td>
                    <td class="align-middle"><span><div class="task-show"><%= link_to "詳細", admin_user_path(user) %></span></div><td>
                    <td class="align-middle"><span><div class="task-edit"><%= link_to "編集", edit_admin_user_path(user) %></span></div></td>
                    <td class="align-middle"><span><div class="task-delete"><%= link_to "削除", admin_user_path(user), method: :delete, data: { confirm:"本当に削除しても良いですか？" } %></span></div></td>
                  </tr>
                </div>
              <% end %>
              <%= paginate @users %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/new.html.erb
<h1>管理者画面　新規ユーザー登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "つのエラー") %> があるので <%= @user.name %> ユーザー登録できません。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, url: admin_users_path) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :admin %>
  <%= f.select :admin, [["なし", "false"],["あり", "true"]],include_blank: "選択" %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "ユーザー登録" %>
<% end %>

app/views/admin/users/show.html.erb
<section class="vh-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                alt="Check" width="60">
                <p><%= notice %></p>
              <h1 class="my-4"><%= @user.name %>のページ</h1>
            </div>
              <p>メールアドレス: <%= @user.email %></p>

              <p>ユーザー権限: <%= @user.admin %></p>

            <table class="table text-white mb-0">
              <thead>
                <tr>
                  <th scope="col"><div class="user">ユーザー</div></th>
                  <th scope="col"><div class="title">タイトル</div></th>
                  <th scope="col"><div class="content">内容</div></th>
                  <th scope="col"><div class="deadline">終了期限</div></th>
                  <th scope="col"><div class="status">状態</div></th>
                  <th scope="col"><div class="priority">優先度</div></th>
                </tr>
              </thead>
              <tbody>
              <% @tasks.each do |task| %>
                <div class="task-preview">
                  <tr class="fw-normal">
                    <td class="align-middle"><span><div class="task-user"><%= task.user.name %></span></div></td>
                    <td class="align-middle"><span><div class="task-title"><%= task.title %></span></div></td>
                    <td class="align-middle"><span><div class="task-content"><%= task.content %></span></div></td>
                    <td class="align-middle"><span><div class="task-deadline"><%= task.deadline %></span></div></td>
                    <td class="align-middle"><span><div class="task-status"><%= task.status_i18n %></span></div></td>
                    <td class="align-middle"><h6 class="mb-0"><span class="badge bg-danger"><div class="task-priority"><%= task.priority_i18n %></span></h6></div></td>
                    <td class="align-middle"><span><div class="task-show"><%= link_to "詳細", task %></span></div><td>
                    <td class="align-middle"><span><div class="task-edit"><%= link_to "編集", edit_task_path(task) %></span></div></td>
                    <td class="align-middle"><span><div class="task-delete"><%= link_to "削除", task, method: :delete, data: { confirm:"本当に削除しても良いですか？" } %></span></div></td>
                  </tr>
                </div>
                <% end %>
                <%= paginate @tasks %>
              </tbody>
            </table>
          </div>
        </div>
        <%= link_to 'ユーザー権限変更', edit_admin_user_path(@user), class: "btn btn-outline-warning" %> |
        <%= link_to 'ユーザー一覧', admin_users_path, class: "btn btn-outline-primary" %> |
      </div>
    </div>
  </div>
</section>

<h1><%= @user.name %>のページ</h1>

  <p>メールアドレス: <%= @user.email %></p>

  <p>ユーザー権限: <%= @user.admin %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスラック</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <section class="vh-100 gradient-custom-2">
      <div class="container py-5 h-100">
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id) %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>
        <%= yield %>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      </div>
    </section>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: @task, local: true, url: choose_new_or_edit ) do |form| %>
  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="task_deadline">
    <%= form.label :deadline %>
    <%= form.date_field :deadline %>
  </div>
    <div class="task_status">
    <%= form.label :status %>
    <%= form.select :status, [["未着手", "waiting"],["着手中", "doing"],["完了", "done"]], include_blank: "選択してください" %>
  </div>
  <div class="task_status">
    <%= form.label :priority %>
    <%= form.select :priority, [["低", "low"],["中", "medium"],["高", "high"]], include_blank: "選択" %>
  </div>
  <div class="task_label">
  <% Label.all.each do |label| %>
    <%= form.check_box :label_ids,{ multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <label style="background-color: gray">
    <%= form.label :label_ids, label.label_name, value: label[:id] %></label>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>
<%= link_to "一覧へ戻る", tasks_path %>
<% end %>

app/views/tasks/edit.html.erb
<section class="vh-100 gradient-custom-2">
  <div class="container py-5 h-200">
    <div class="row d-flex justify-content-center align-items-center h-200">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                alt="Check" width="60">
              <h2 class="my-4">タスク編集</h2>
            </div>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/index.html.erb
<section class="vh-100 gradient-custom-2">
  <div class="container py-5 h-200">
    <div class="row d-flex justify-content-center align-items-center h-200">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                alt="Check" width="60">
              <h2 class="my-4">タスク一覧</h2>
            </div>
            <p><%= notice %></p>
              <div class="search-form">
                <%= form_with(scope: :search, url: tasks_path, local: true, method: :get) do |f| %>
                  <%= f.label :タイトル検索 %>
                  <%= f.text_field :title %>
                  <%= f.label :状態検索 %>
                  <%= f.select :status, [["未選択",""],["未着手", 0],["着手中", 1],["完了", 2]]%>
                  <%= f.label :ラベル検索　%>
                  <%= f.select("label_id", Label.pluck(:label_name, :id), { include_blank: true }) %>
                  <%= f.submit "検索", class: "btn btn-secondary"%>
                <% end %>
              </div>
            <table class="table text-white mb-0">
              <thead>
                <tr>
                  <div class="text-bg-primary p-3">
                  <th scope="col"><div class="user "><%= sort_order "user", "ユーザー" %></div></th>
                  <th scope="col"><div class="title"><%= sort_order "title", "タイトル" %></div></th>
                  <th scope="col"><div class="content"><%= sort_order "content", "内容" %></div></th>
                  <th scope="col"><div class="deadline"><%= sort_order "deadline", "終了期限" %></div></th>
                  <th scope="col"><div class="status"><%= sort_order "status", "状態" %></div></th>
                  <th scope="col"><div class="priority"><%= sort_order "priority", "優先度" %></div></th>
                  </div>
                </tr>
              </thead>
              <tbody>
              <% @tasks.each do |task| %>
                <div class="task-preview">
                  <tr class="fw-normal">
                    <td class="align-middle"><span><div class="task-user"><%= task.user.name %></span></div></td>
                    <td class="align-middle"><span><div class="task-title"><%= task.title %></span></div></td>
                    <td class="align-middle"><span><div class="task-content"><%= task.content %></span></div></td>
                    <td class="align-middle"><span><div class="task-deadline"><%= task.deadline %></span></div></td>
                    <td class="align-middle"><span><div class="task-status"><%= task.status_i18n %></span></div></td>
                    <td class="align-middle"><h6 class="mb-0"><span class="badge bg-danger"><div class="task-priority"><%= task.priority_i18n %></span></h6></div></td>
                    <td class="align-middle"><span><div class="task-show"><%= link_to task do %>
                      <i class="fas fa-check fa-lg text-success me-3" value="詳細"></i>
                    <% end %></span></div><td>
                    <td class="align-middle"><span><div class="task-edit"><%= link_to edit_task_path(task) do %>
                      <i class="fas fa-edit fa-lg text-warning me-3"></i>
                    <% end %></span></div></td>
                    <td class="align-middle"><span><div class="task-delete"><%= link_to task, method: :delete, data: { confirm:"本当に削除しても良いですか？" } do %>
                      <i class="fas fa-trash-alt fa-lg text-danger"></i>
                    <% end %></span></div></td>
                  </tr>
                </div>
                <% end %>
                <%= paginate @tasks %>
              </tbody>
            </table>
          </div>
        </div>
        <%= link_to '新規タスク作成', new_task_path %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="vh-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                alt="Check" width="60">
                <p><%= notice %></p>
                  <h1><%= @user.name %>のページ</h1>
                    <p>メールアドレス: <%= @user.email %></p>

                    <% if current_user.admin? %>
                      <p>管理者権限: あり</p>
                        <%= link_to 'ユーザー管理画面', admin_users_path, class: "btn btn-outline-primary" %> |
                        <%= link_to "新規タスク作成", new_task_path, class: "btn btn-primary" %> |
                        <%= link_to 'ユーザー情報変更', edit_user_path(@user), class: "btn btn-outline-warning" %> |
                        <%= link_to 'タスク一覧', tasks_path, class: "btn btn-outline-primary" %> |
                      <% else %>
                      <p>管理者権限: なし</p>
                        <%= link_to "新規タスク作成", new_task_path, class: "btn btn-primary" %> |
                        <%= link_to 'ユーザー情報変更', edit_user_path(@user), class: "btn btn-outline-warning" %> |
                        <%= link_to 'タスク一覧', tasks_path, class: "btn btn-outline-primary" %> |
                    <% end %>

            <table class="table text-white mb-0">
              <thead>
                <tr>
                  <th scope="col"><div class="user">ユーザー</div></th>
                  <th scope="col"><div class="title">タイトル</div></th>
                  <th scope="col"><div class="content">内容</div></th>
                  <th scope="col"><div class="deadline">終了期限</div></th>
                  <th scope="col"><div class="status">状態</div></th>
                  <th scope="col"><div class="priority">優先度</div></th>
                </tr>
              </thead>
              <tbody>
              <% @tasks.each do |task| %>
                <div class="task-preview">
                  <tr class="fw-normal">
                    <td class="align-middle"><span><div class="task-user"><%= task.user.name %></span></div></td>
                    <td class="align-middle"><span><div class="task-title"><%= task.title %></span></div></td>
                    <td class="align-middle"><span><div class="task-content"><%= task.content %></span></div></td>
                    <td class="align-middle"><span><div class="task-deadline"><%= task.deadline %></span></div></td>
                    <td class="align-middle"><span><div class="task-status"><%= task.status_i18n %></span></div></td>
                    <td class="align-middle"><h6 class="mb-0"><span class="badge bg-danger"><div class="task-priority"><%= task.priority_i18n %></span></h6></div></td>
                    <td class="align-middle"><span><div class="task-show"><%= link_to "詳細", task %></span></div><td>
                    <td class="align-middle"><span><div class="task-edit"><%= link_to "編集", edit_task_path(task) %></span></div></td>
                    <td class="align-middle"><span><div class="task-delete"><%= link_to "削除", task, method: :delete, data: { confirm:"本当に削除しても良いですか？" } %></span></div></td>
                  </tr>
                </div>
                <% end %>
                <%= paginate @tasks %>
              </tbody>
            </table>
            <%= link_to "一覧へ戻る", tasks_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>